### PR TITLE
Specify supported environment for Application Insights JS SDK

### PR DESCRIPTION
**Pull request by pizzaz93**
## Purpose
One item in https://github.com/microsoft/ApplicationInsights-JS/issues/1792

## Does this introduce a breaking change?

```
[ ] Yes
[X ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by pizzaz93** [comment]
@jpiyali

**Comment by pizzaz93** [comment]
Since there hasn't been a response, closing.

**Comment by hectorhdzg** [comment]
@pizzaz93 looks like this sample app is quite old and using older version of Application Insights SDKs, please take a look at current version [here](https://github.com/microsoft/ApplicationInsights-JS)

**Comment by pizzaz93** [comment]
Thank you @hectorhdzg, this PR was specific to a customer concern detailed in https://github.com/microsoft/ApplicationInsights-JS/issues/1792, which was in regards to updating this sample app's code comment.

**Pull request closed without merging**
